

telegraf:
  image: juniper/nfd14-demo-oc-telemetry
  command: /go/bin/telegraf -debug
  volumes:
   - ./telegraf-influxdb.toml:/etc/telegraf/telegraf.conf
   - /etc/localtime:/etc/localtime
  links:
   - influxdb

grafana:
  image: grafana/grafana:4.1.1
  environment:
   - "GF_SECURITY_ADMIN_PASSWORD=admin"
  volumes:
   - /etc/localtime:/etc/localtime
  ports:
   - "3000:3000"
  links:
   - influxdb

influxdb:
  image: influxdb:1.1-alpine
  volumes:
   - ./dashboard.json:/src/dashboards/dashboard.json
   - /etc/localtime:/etc/localtime
  ports:
   - "8083:8083"
   - "8086:8086"
